[package]
name = "ascii_art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
termion = "3.0.0"
opencv = "0.90.0"
